[package]
name = "http1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.5"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "parser"
harness = false
